### ISSUE TITLE
I used today's version and still have bugs.

### ISSUE THREAD

**Issue by do02fw** [alirezamarzban/ocserv-with-user-management#4]
I used today's version and still have bugs. 404 not found.
<img width="914" alt="1" src="https://github.com/alirezamarzban/ocserv-with-user-management/assets/138294823/8bc66c1f-00d9-455f-805e-0ec309b94793">

**Comment by alirezamarzban** [comment]
what do you mean exactly, when your getting this error?

**Comment by do02fw** [comment]
> what do you mean exactly, when your getting this error?

I can't use the script to install the dependency environment because the installation source is not found for ipv6 access.

**Comment by alirezamarzban** [comment]
if it's possible, please send screenshot, in whitch vps provider you have problem?

**Comment by do02fw** [comment]
> if it's possible, please send screenshot, in whitch vps provider you have problem?

IF MY SERVER DOES NOT HAVE AN IPV6 NETWORK, THERE WILL BE NO 404 NOT FOUND, IF THERE IS AN IPV6 NETWORK, THE IPV6 NETWORK WILL BE USED FIRST TO UPDATE THE INSTALLATION SOURCE, IF THE IPV6 UPDATE MAY APPEAR 404 NOT FOUND, YOU CAN FIND A SERVER WITH IPV4 + IPV6 TO TEST IT.

**Comment by alirezamarzban** [comment]
please check it now

**Comment by do02fw** [comment]
> please check it now

I have now switched to the debian11 system, I used another script, docker, and now without any issues.

**Comment by alirezamarzban** [comment]
i updated the script

**Comment by do02fw** [comment]
> i updated the script

GOOD！I got it to install this time, Ubuntu 20.04, but I see the warning message during the installation, can you add the IPV6 feature of ocserv?
![6](https://github.com/alirezamarzban/ocserv-with-user-management/assets/138294823/a23efcc9-e1a0-4744-ad2b-de81fc6c1bb8)
![7](https://github.com/alirezamarzban/ocserv-with-user-management/assets/138294823/2cc3bbfe-c560-4504-9809-3a03232939d8)
![8](https://github.com/alirezamarzban/ocserv-with-user-management/assets/138294823/f990a284-972a-4e4a-96c8-c02de6cc17e0)
![9](https://github.com/alirezamarzban/ocserv-with-user-management/assets/138294823/5529c0ed-385d-464e-8048-91cd33c2d9b9)

**Comment by do02fw** [comment]
I updated my system to Ubuntu 20.04 and I don't have this problem anymore, I can boot my system normally.

**Comment by alirezamarzban** [comment]
in which os you had such a issues?

**Comment by do02fw** [comment]
> 您在哪个操作系统中遇到此类问题？



> in which os you had such a issues?

I had this problem with ubuntu 20.04, I consulted the cloud server vendor and they replied to me that their system was not configured with python environment and variables, when I upgraded from 20.04 to 22.04 and then installed the script without any problems, I think the vendor has made changes or streamlined the system to cause this. If you can, you could add something to the script that detects environment variables and automatically fixes them, and that would solve the situation.

**Comment by do02fw** [comment]
Do you know how to get ocserv to give priority to ipv6? When I connect to anyconnecy and use the ping command, it returns ipv4 results first, unless I add -6 to the ping it will return ipv6 results, how do I get ocserv to use ipv6 first?
![7](https://github.com/alirezamarzban/ocserv-with-user-management/assets/138294823/9242ff15-b8af-4bba-a5c6-782cd8be87a8)

**Comment by alirezamarzban** [comment]
to enable ipv6, you must:
nano /etc/sysctl.conf
find this line:
#net.ipv6.conf.all.forwarding=1
change it to:
net.ipv6.conf.all.forwarding=1
then presse ctrl + x and press y and presse enter to save the changes
then run this command:
sysctl -p
then go to ocserv.conf by this command:
nano /etc/ocserv/ocserv.conf
find this line:
#ipv6-network = fda9:4efe:7e3b:03ea::/48 
change it to:
ipv6-network = fda9:4efe:7e3b:03ea::/48
now find this line:
#ipv6-subnet-prefix = 128
or
#ipv6-subnet-prefix = 64
change it to:
ipv6-subnet-prefix = 128
or
ipv6-subnet-prefix = 64
then restart ocserv to take the effects by using script, or use this command:
systemctl restart ocserv
all is done

**Comment by do02fw** [comment]
> to enable ipv6, you must: nano /etc/sysctl.conf find this line: #net.ipv6.conf.all.forwarding=1 change it to: net.ipv6.conf.all.forwarding=1 then presse ctrl + x and press y and presse enter to save the changes then run this command: sysctl -p then go to ocserv.conf by this command: nano /etc/ocserv/ocserv.conf find this line: #ipv6-network = fda9:4efe:7e3b:03ea::/48 change it to: ipv6-network = fda9:4efe:7e3b:03ea::/48 now find this line: #ipv6-subnet-prefix = 128 or #ipv6-subnet-prefix = 64 change it to: ipv6-subnet-prefix = 128 or ipv6-subnet-prefix = 64 then restart ocserv to take the effects by using script, or use this command: systemctl restart ocserv all is done

Thanks, I have enabled IPV6, but it has a low priority, when I access the internet, it will give priority to ipv4, how can I modify the route to increase the priority of ipv6?
